apiVersion: v1
kind: Service
metadata:
  name: website-khan-service
  namespace: default
spec:
  selector:
    app: website-khan
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
