apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-khan
  namespace: default
  labels:
    app: website-khan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website-khan
  template:
    metadata:
      labels:
        app: website-khan
    spec:
      containers:
      - name: website-khan
        image: khanecr.azurecr.io/website-khan:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
